// Dev harness for M4.1 (PLAN.md §4). NOT a unit test — it replays real match
// history through the pure seeding engine and writes the dry-run report
// docs/matchmaking-v2/seed-ratings.md plus a write payload for the apply step.
//
// It never writes to any database. PLAN §5: the production write stays a
// manual, owner-triggered step.
//
// Skipped unless MM_SEED_FIXTURE points at a JSON snapshot of production
// { players, aliases, tournaments, matches } (pulled read-only, kept out of
// git). Reproduce with:
//   MM_SEED_FIXTURE=/path/to/mm-seed-fixture.json \
//     npx vitest run src/features/matchmaking/domain/rating/seed.harness.test.ts
//
// The payload lands next to the fixture as <fixture>.payload.json.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { describe, it, expect } from 'vitest'
import { ratingToPadel } from '../../../../lib/glicko2'
import { buildReplayDataset, type Fixture } from '../../historyFixture'
import { DEFAULT_RATING_PARAMS } from '../types'
import { seedOutliers, seedRatingsFromHistory, type SeededRating } from './seed'

const FIXTURE = process.env.MM_SEED_FIXTURE
const OUTLIER_THRESHOLD = 0.4 // levels of divergence from the V1 learned level
const MIGRATION_NAME = '20260725000001_mm_seed_ratings.sql'

const run = FIXTURE ? describe : describe.skip

function seedFrom({ fixture, includeHistory }: { fixture: Fixture; includeHistory: boolean }) {
  const dataset = buildReplayDataset({ fixture, includeHistory })
  const players = dataset.participants.map((playerId) => ({
    playerId,
    playtomicLevel: dataset.levelByPlayerId[playerId],
  }))
  return { dataset, seeded: seedRatingsFromHistory({ players, events: dataset.events }) }
}

const sqlNumber = (n: number) => n.toFixed(6)
const sqlString = (s: string) => `'${s.replace(/'/g, "''")}'`

/**
 * D-031: the seed lands as one UPDATE per player plus one `kind = 'seed'`
 * provenance row, not as a per-tournament RPC replay. Both statements are
 * guarded so the migration is a safe no-op anywhere the player row is absent
 * (local `db:reset`) or already rated (an event finished before the push).
 */
function buildSeedMigration({
  seeded,
  labelByEventId,
  eventCount,
}: {
  seeded: SeededRating[]
  labelByEventId: Map<string, string>
  eventCount: number
}): string {
  const rows = seeded.map((r) => {
    const proposedTotal = r.history.reduce((s, h) => s + h.proposedDelta, 0)
    const breakdown = r.history.map((h) => ({
      event: labelByEventId.get(h.eventId) ?? h.eventId,
      eventId: h.eventId,
      matches: h.matchCount,
      priorMu: Number(h.priorMu.toFixed(6)),
      priorSigma: Number(h.priorSigma.toFixed(6)),
      proposedDelta: Number(h.proposedDelta.toFixed(6)),
      appliedDelta: Number(h.appliedDelta.toFixed(6)),
      flags: h.flags,
      newMu: Number(h.newMu.toFixed(6)),
      newSigma: Number(h.newSigma.toFixed(6)),
    }))
    return (
      `    (${sqlString(r.playerId)}::uuid, ${sqlNumber(r.playtomicLevel)}, ` +
      `${sqlNumber(r.mu)}, ${sqlNumber(r.sigma)}, ${sqlNumber(proposedTotal)}, ` +
      `${sqlString(JSON.stringify(breakdown))}::jsonb)`
    )
  })

  return `-- ============================================================================
-- M4.1 — Seed learned ratings from full match history (PLAN.md §4, D-031)
--
-- Generated by src/features/matchmaking/domain/rating/seed.harness.test.ts from
-- a read-only production snapshot. Do not hand-edit: regenerate by re-running
-- that harness. The dry-run report the owner reviewed is
-- docs/matchmaking-v2/seed-ratings.md.
--
-- Every value below is the mu/sigma left after replaying that player's history
-- through the same updateRatingsForTournament → applyGuardrails composition the
-- live Finish path runs: ${seeded.length} players over ${eventCount} production events, capped
-- at ±0.30 per event. History.jsx matches are excluded (D-032). Until this lands
-- every player enters their first V2 event at the raw playtomic_level prior and
-- the admin drawer's "Learned level" row stays hidden.
--
-- Why a direct UPDATE rather than admin_apply_tournament_ratings once per
-- historical tournament (D-031, amended by D-032): with History excluded all
-- ${eventCount} replayed events do have tournaments rows, so the RPC path is no longer
-- impossible — it is now a deliberate choice. It would permanently trip the
-- RPC's double-apply guard on these ${eventCount} tournaments (a re-seed would need row
-- deletion first) and stamp every event with the same mm_rating_updated_at
-- anyway. Provenance lands instead as one kind = 'seed' row per player carrying
-- the whole replay. Revisit if per-match historical breakdowns are ever wanted
-- in the admin UI.
--
-- Safety: both statements no-op where the player row is absent (local db:reset
-- has none of these ids) and where mm_rating is already set (an event finished
-- between generating this file and pushing it — live values always win).
-- ============================================================================

BEGIN;

WITH seed(player_id, playtomic_level, new_mu, new_sigma, proposed_total, breakdown) AS (
  VALUES
${rows.join(',\n')}
),
applied AS (
  UPDATE public.players p
     SET mm_rating            = s.new_mu,
         mm_sigma             = s.new_sigma,
         mm_rating_updated_at = now()
    FROM seed s
   WHERE p.id = s.player_id
     AND p.mm_rating IS NULL
  RETURNING p.id, s.playtomic_level, s.new_mu, s.proposed_total, s.breakdown
)
-- One provenance row per seeded player. kind = 'seed' joins the existing
-- 'tournament' | 'self_reset' | 'admin_edit' vocabulary. tournament_id is null
-- (this spans six events, two of which are not tournaments rows); prior_sigma is
-- the SIGMA_PRIOR every replay started from; breakdown is a per-event summary
-- rather than the per-match rows a 'tournament' row carries. flagged = false, so
-- these never enter the admin review queue.
INSERT INTO public.rating_events (
  kind, tournament_id, player_id, prior_mu, prior_sigma,
  proposed_delta, applied_delta, flagged, review_status, breakdown
)
SELECT 'seed', NULL, a.id, a.playtomic_level, 0.7,
       a.proposed_total, a.new_mu - a.playtomic_level, false, NULL, a.breakdown
  FROM applied a;

COMMIT;
`
}

run('M4.1 seeding harness', () => {
  it('replays full history and writes the dry-run report', () => {
    const fixture: Fixture = JSON.parse(readFileSync(FIXTURE!, 'utf8'))
    const nameById = new Map(fixture.players.map((p) => [p.id, p.name ?? p.id]))
    const fmt = (n: number, d = 3) => n.toFixed(d)

    // The report is committed to a PUBLIC repo, so it must not publish a named
    // skill ranking of real people — D-017 keeps mm_* admin-only precisely so a
    // learned level is never a player-facing score. Rows key on the uuid prefix
    // instead, which joins to the generated migration, so an admin can still
    // resolve anyone. Set MM_SEED_NAMES=1 for a local, un-redacted read; never
    // commit that output.
    const showNames = process.env.MM_SEED_NAMES === '1'
    const name = (id: string) => (showNames ? (nameById.get(id) ?? id) : id.slice(0, 8))

    const withHistory = seedFrom({ fixture, includeHistory: true })
    const prodOnly = seedFrom({ fixture, includeHistory: false })

    // Legacy V1 comparison: learned_rating is Glicko-scale; ratingToPadel maps
    // it back to the level units mm_rating lives in (1500 → 3.0, 100 pts = 1.0).
    const legacyLevelByPlayerId: Record<string, number> = {}
    for (const p of fixture.players) {
      if (p.learned_rating != null)
        legacyLevelByPlayerId[p.id] = ratingToPadel(Number(p.learned_rating))
    }

    // D-032: production matches only. The owner reviewed both replays and
    // recognised the production-only numbers as the ones matching how these
    // players actually play. `withHistory` stays computed so the report can keep
    // showing what the rejected alternative would have done.
    const chosen = prodOnly
    const outliers = seedOutliers({
      seeded: chosen.seeded,
      legacyLevelByPlayerId,
      threshold: OUTLIER_THRESHOLD,
    })

    const byId = (rows: SeededRating[]) => new Map(rows.map((r) => [r.playerId, r]))
    const chosenById = byId(chosen.seeded)
    const sourceDiffs = withHistory.seeded
      .map((r) => ({ row: r, shipped: chosenById.get(r.playerId) }))
      .filter((d) => d.shipped)
      .map((d) => ({ playerId: d.row.playerId, delta: d.row.mu - d.shipped!.mu }))
      .sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta))
    // Players History would have seeded but the shipped replay does not.
    const onlyWithHistory = withHistory.seeded.filter((r) => !chosenById.has(r.playerId))

    const flaggedTotal = chosen.seeded.reduce((s, r) => s + r.flaggedEvents, 0)
    const flagCounts = { over_cap: 0, drift: 0, oscillation: 0 }
    for (const r of chosen.seeded) {
      for (const h of r.history) for (const f of h.flags) flagCounts[f]++
    }

    const sortedEvents = [...chosen.dataset.events].sort((a, b) => a.sortKey - b.sortKey)
    const noLegacy = chosen.seeded.filter((r) => legacyLevelByPlayerId[r.playerId] == null)
    const comparable = chosen.seeded.length - noLegacy.length
    const absDiffs = chosen.seeded
      .filter((r) => legacyLevelByPlayerId[r.playerId] != null)
      .map((r) => Math.abs(r.mu - legacyLevelByPlayerId[r.playerId]))
      .sort((a, b) => a - b)
    const median = absDiffs.length ? absDiffs[Math.floor((absDiffs.length - 1) / 2)] : 0

    // Direction agreement: ignoring magnitude, do the two models agree on which
    // side of the self-reported level a player sits? This survives the fact that
    // V1 (uncapped Glicko) swings far harder than V2 (±0.30/event), so raw
    // distance mostly measures the model change rather than an error in either.
    const directional = chosen.seeded.filter((r) => {
      const legacy = legacyLevelByPlayerId[r.playerId]
      if (legacy == null) return false
      return Math.abs(r.mu - r.playtomicLevel) > 0.05 && Math.abs(legacy - r.playtomicLevel) > 0.05
    })
    const agreeing = directional.filter(
      (r) =>
        Math.sign(r.mu - r.playtomicLevel) ===
        Math.sign(legacyLevelByPlayerId[r.playerId] - r.playtomicLevel),
    )

    // V1 values outside any level a padel player could hold. Their existence is
    // the reason distance-from-V1 cannot be read as distance-from-truth.
    const legacyImplausible = chosen.seeded.filter((r) => {
      const legacy = legacyLevelByPlayerId[r.playerId]
      return legacy != null && (legacy < 0.5 || legacy > 5)
    })

    // playtomic_level = 0 is almost certainly "never set", not a real level; it
    // anchors the whole replay for that player.
    const zeroLevel = chosen.seeded.filter((r) => r.playtomicLevel === 0)
    const shifts = chosen.seeded.map((r) => Math.abs(r.mu - r.playtomicLevel))
    const maxShift = Math.max(...shifts)

    const lines: string[] = []
    const push = (...s: string[]) => lines.push(...s)

    push('# Matchmaking V2 — Rating Seed Dry Run (M4.1)')
    push('')
    push(
      'Generated by `seed.harness.test.ts` from a read-only production snapshot on ' +
        new Date().toISOString().slice(0, 10) +
        '. **Nothing has been written.**',
    )
    push('')
    if (!showNames) {
      push(
        'Players are keyed by the first 8 characters of their id, not by name — this file' +
          ' is committed to a public repo and a learned level is admin-only (D-017). The' +
          ' prefixes join to `supabase/migrations/20260725000001_mm_seed_ratings.sql`.' +
          ' Re-run the harness with `MM_SEED_NAMES=1` for a local named copy.',
      )
      push('')
    }
    push('Every player below is replayed from `initialRating({ playtomicLevel })` through')
    push('every completed event in date order, each event running the same')
    push('`updateRatingsForTournament → applyGuardrails` composition the live Finish path')
    push('runs, carrying the posterior forward as the next event’s prior. `mu` advances by')
    push('the **capped** `appliedDelta` only; withheld remainders are listed as flags.')
    push('')

    push('## Dataset')
    push('')
    push(`- Production matches replayed: **${chosen.dataset.stats.productionKept}**`)
    push(
      `- History.jsx matches: **excluded** (D-032) — the ${withHistory.dataset.stats.historyKept} ` +
        `alias-linked ones the owner rejected, plus ${withHistory.dataset.stats.historyDropped} ` +
        'that were never attributable anyway (D-010)',
    )
    push(`- Events replayed: **${chosen.dataset.events.length}**`)
    push(
      `- Players receiving a seed: **${chosen.seeded.length}** of ${fixture.players.length} in the roster`,
    )
    push(`- Players with a V1 \`learned_rating\` to compare against: **${comparable}**`)
    push('')

    push('## Events (chronological)')
    push('')
    push('| # | event | source | matches | players updated | flagged |')
    push('| --- | --- | --- | --- | --- | --- |')
    sortedEvents.forEach((ev, i) => {
      const rows = chosen.seeded.flatMap((r) => r.history.filter((h) => h.eventId === ev.eventId))
      push(
        `| ${i + 1} | ${ev.label} | ${ev.source} | ${ev.matches.length} | ${rows.length} | ` +
          `${rows.filter((h) => h.flags.length > 0).length} |`,
      )
    })
    push('')

    push('## Guardrails fired during the replay')
    push('')
    push(`- Player-events with at least one flag: **${flaggedTotal}**`)
    push(
      `- \`over_cap\`: ${flagCounts.over_cap} · \`drift\`: ${flagCounts.drift} · \`oscillation\`: ${flagCounts.oscillation}`,
    )
    push('')

    push('## Plausibility of the seed itself')
    push('')
    push(
      `The seed is anchored: a player can move at most ±0.30 per event, so after ` +
        `1–${chosen.dataset.events.length} events nobody can be far from their self-reported`,
    )
    push('level. This is the first thing to check, because it is the number that ships.')
    push('')
    push(`- Largest shift from playtomic level, any player: **${fmt(maxShift)}** levels`)
    push(
      `- Sigma range: **${fmt(Math.min(...chosen.seeded.map((r) => r.sigma)))} – ${fmt(Math.max(...chosen.seeded.map((r) => r.sigma)))}**`,
    )
    push(
      `- Players still above the 0.5 "provisional level" mark (📏 in the schedule): ` +
        `**${chosen.seeded.filter((r) => r.sigma >= 0.5).length}**`,
    )
    push('')
    if (zeroLevel.length > 0) {
      push(
        '**Data-quality flag.** ' +
          `${zeroLevel.length} seeded player(s) have \`playtomic_level = 0\`, which is` +
          ' almost certainly "never set" rather than a real level — and it anchors their' +
          ' whole replay:',
      )
      push('')
      for (const r of zeroLevel) {
        push(
          `- **${name(r.playerId)}** — seeded mu ${fmt(r.mu)} (σ ${fmt(r.sigma)}), ` +
            `${r.matchesPlayed} matches over ${r.eventsPlayed} events.`,
        )
      }
      push('')
      push('Fixing the level first and re-running would give a truer seed than seeding off 0.')
      push('')
    }

    push('## Sanity check against the V1 learned level')
    push('')
    push('`learned_rating` is Glicko-scale; compared here as `ratingToPadel` levels')
    push('(1500 → 3.0). **Read this as a cross-check, not as an error measure.** V1 is')
    push('uncapped Glicko-2 from a 350 RD start, so it swings several levels in a handful')
    push('of events; V2 moves at most 0.30 per event by design. Distance between them')
    push('therefore mostly measures the model change that D-010 deliberately made (V2')
    push('Brier 0.0541 vs Glicko 0.0577 on the same replay).')
    push('')
    push(
      `- Median |seeded − V1| across ${comparable} comparable players: **${fmt(median, 2)}** levels`,
    )
    push(`- Above the ${OUTLIER_THRESHOLD}-level threshold: **${outliers.length}**`)
    push(`- No V1 rating to compare: **${noLegacy.length}**`)
    push(
      `- **Direction agreement** (both models moved the player off their playtomic level — ` +
        `do they agree which way?): **${agreeing.length} / ${directional.length}** ` +
        `(${directional.length ? Math.round((100 * agreeing.length) / directional.length) : 0}%)`,
    )
    if (legacyImplausible.length > 0) {
      push(
        `- **V1 values outside any real level (< 0.5 or > 5): ${legacyImplausible.length}** — ` +
          legacyImplausible
            .map((r) => `${name(r.playerId)} ${fmt(legacyLevelByPlayerId[r.playerId], 2)}`)
            .join(', ') +
          '. Nothing in V2 lands anywhere near these, which is the point of the cap.',
      )
    }
    push('')
    push(`### Largest divergence from V1 (> ${OUTLIER_THRESHOLD} levels) — owner review`)
    push('')
    push('| player | playtomic | seeded mu | V1 level | diff | events | matches |')
    push('| --- | --- | --- | --- | --- | --- | --- |')
    for (const o of outliers) {
      push(
        `| ${name(o.playerId)} | ${fmt(o.playtomicLevel, 2)} | ${fmt(o.seededMu)} | ` +
          `${fmt(o.legacyLevel)} | ${o.delta > 0 ? '+' : ''}${fmt(o.delta)} | ${o.eventsPlayed} | ${o.matchesPlayed} |`,
      )
    }
    push('')

    push('## Full seed table')
    push('')
    push(
      '| player | playtomic | seeded mu | shift vs playtomic | sigma | events | matches | flagged |',
    )
    push('| --- | --- | --- | --- | --- | --- | --- | --- |')
    for (const r of [...chosen.seeded].sort((a, b) => b.mu - a.mu)) {
      const shift = r.mu - r.playtomicLevel
      push(
        `| ${name(r.playerId)} | ${fmt(r.playtomicLevel, 2)} | ${fmt(r.mu)} | ` +
          `${shift > 0 ? '+' : ''}${fmt(shift)} | ${fmt(r.sigma)} | ${r.eventsPlayed} | ` +
          `${r.matchesPlayed} | ${r.flaggedEvents} |`,
      )
    }
    push('')

    push('## Source: production matches only (D-032)')
    push('')
    push('The owner reviewed both replays and recognised the **production-only** numbers as')
    push('the ones matching how these players actually play; the History.jsx variant is')
    push('rejected. This entry keeps the comparison so the call stays checkable.')
    push('')
    push(
      `- **Shipped — production only:** ${chosen.seeded.length} players seeded across ` +
        `${chosen.dataset.events.length} events (${chosen.dataset.stats.productionKept} matches).`,
    )
    push(
      `- **Rejected — plus ${withHistory.dataset.stats.historyKept} alias-linked History matches:** ` +
        `${withHistory.seeded.length} players across ${withHistory.dataset.events.length} events.`,
    )
    push(
      `- **Cost of the choice: ${onlyWithHistory.length} players get no seed at all** and enter ` +
        'their next event on the raw playtomic prior' +
        (onlyWithHistory.length
          ? ' — ' + onlyWithHistory.map((r) => name(r.playerId)).join(', ')
          : ''),
    )
    push('')
    push('| player | shipped (production only) | rejected (with History) | diff |')
    push('| --- | --- | --- | --- |')
    for (const d of sourceDiffs.slice(0, 20)) {
      const shipped = chosenById.get(d.playerId)!
      const alt = withHistory.seeded.find((r) => r.playerId === d.playerId)!
      push(
        `| ${name(d.playerId)} | ${fmt(shipped.mu)} | ${fmt(alt.mu)} | ` +
          `${-d.delta > 0 ? '+' : ''}${fmt(-d.delta)} |`,
      )
    }
    push('')
    push(
      `Largest single divergence between the two replays: **${fmt(Math.abs(sourceDiffs[0]?.delta ?? 0))}** levels.`,
    )
    push('')

    push('## Method notes')
    push('')
    push('- **Capped deltas only.** A player whose event delta exceeded ±0.30 moved 0.30 and')
    push('  the remainder was withheld — exactly as live. Seeding does not retroactively')
    push('  approve remainders; that is what the review queue is for.')
    push('- **No sigma inactivity inflation.** `inflateForInactivity` is not applied: the')
    push('  live path never calls it, so applying it while seeding would invent a policy no')
    push('  later event maintains. Worth revisiting as its own decision.')
    push('- **Skipped rows.** Zero-total matches, matches with a player missing from the')
    push('  roster, and matches with the same player twice are skipped, not fatal.')
    push('- **Players with no match history get no row** — a null `mm_rating` already means')
    push('  "fall back to the playtomic prior", which is the correct seed for them.')
    push('')

    const outPath = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      '../../../../../docs/matchmaking-v2/seed-ratings.md',
    )
    writeFileSync(outPath, lines.join('\n'))

    // Write payload for the apply step: final mu/sigma per player, both variants.
    const payloadPath = FIXTURE!.replace(/\.json$/, '') + '.payload.json'
    writeFileSync(
      payloadPath,
      JSON.stringify(
        {
          generatedAt: new Date().toISOString(),
          params: DEFAULT_RATING_PARAMS,
          withHistory: chosen.seeded,
          productionOnly: prodOnly.seeded,
        },
        null,
        2,
      ),
    )

    const migrationPath = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      '../../../../../supabase/migrations/' + MIGRATION_NAME,
    )
    writeFileSync(
      migrationPath,
      buildSeedMigration({
        seeded: chosen.seeded,
        labelByEventId: new Map(chosen.dataset.events.map((e) => [e.eventId, e.label])),
        eventCount: chosen.dataset.events.length,
      }),
    )

    console.log(
      `\n[seed] events=${chosen.dataset.events.length} seeded=${chosen.seeded.length} ` +
        `flagged=${flaggedTotal} outliers=${outliers.length} medianVsV1=${fmt(median, 2)}\n` +
        `[seed] wrote ${outPath}\n[seed] wrote ${payloadPath}\n[seed] wrote ${migrationPath}`,
    )

    expect(chosen.seeded.length).toBeGreaterThan(0)
    expect(chosen.dataset.stats.productionKept).toBeGreaterThan(0)
  })
})
