import { describe, expect, it } from 'vitest'
import { auditFeasibility } from './feasibility'
import { generateSchedule } from './generate'
import { resolveConfig } from './presets'
import { DEFAULT_MAX_BALANCE_DELTA, scheduleFromRun, suggestOpponentSwaps } from './swaps'
import { assertHardLegal, mkRoster } from './testkit'
import { scheduleRunSchema } from './types'
import type { GenderMode, ScheduleRun } from './types'

// M3.8 acceptance suite (coordinator-frozen; worker removes `.skip` and
// implements swaps.ts to green). Inputs are generated by the real pipeline so
// the fixtures are hard-legal and the reconstructed baseline is exercised.

const TOURNAMENT = 't-swaps'
const GENDER: GenderMode = 'men'

// 8 players / 2 courts / 5 rounds, no sitters: 40 opposing-pair meetings over
// only C(8,2)=28 distinct pairs, so opponent rematches are guaranteed.
function setup() {
  const players = mkRoster({ count: 8, muTop: 4.2, muStep: 0.15 })
  const courts = 2
  const rounds = 5
  const config = { preset: 'balanced' as const, seed: 7 }
  const resolved = resolveConfig({ config, tournamentId: TOURNAMENT })
  const feasibility = auditFeasibility({
    players,
    courts,
    rounds,
    genderMode: GENDER,
    config: resolved,
  })
  const run = generateSchedule({
    tournamentId: TOURNAMENT,
    players,
    courts,
    rounds,
    genderMode: GENDER,
    config,
  })
  return { players, feasibility, run }
}

const pairKey = (a: string, b: string) => (a < b ? `${a}|${b}` : `${b}|${a}`)

/** First opposing pair that meets for the 2nd+ time, with the round it recurs in. */
function firstRematch(run: ScheduleRun): { roundIndex: number; pair: [string, string] } {
  const meetings = new Map<string, number>()
  for (let r = 0; r < run.rounds.length; r++) {
    for (const court of run.rounds[r].courts) {
      for (const a of court.teams[0]) {
        for (const b of court.teams[1]) {
          const key = pairKey(a, b)
          const n = (meetings.get(key) ?? 0) + 1
          meetings.set(key, n)
          if (n >= 2) return { roundIndex: r, pair: [a, b] }
        }
      }
    }
  }
  throw new Error('fixture has no rematch — adjust setup()')
}

/** Whether a and b are opposing each other on some court in the given round. */
function areOpponents(run: ScheduleRun, roundIndex: number, a: string, b: string): boolean {
  return run.rounds[roundIndex].courts.some(
    (c) =>
      (c.teams[0].includes(a) && c.teams[1].includes(b)) ||
      (c.teams[0].includes(b) && c.teams[1].includes(a)),
  )
}

const sitterIds = (run: ScheduleRun) => run.rounds.map((r) => r.sitters.map((s) => s.playerId))

describe('suggestOpponentSwaps (M3.8)', () => {
  it('returns at least one swap that breaks a genuine rematch', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    expect(suggestions.length).toBeGreaterThan(0)
  })

  it('every returned suggestion breaks the targeted pair in that round', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    for (const s of suggestions) {
      expect(s.breaksTarget).toBe(true)
      expect(areOpponents(s.run, roundIndex, pair[0], pair[1])).toBe(false)
    }
  })

  it('never returns a hard-illegal schedule', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    for (const s of suggestions) {
      expect(() =>
        assertHardLegal({ schedule: scheduleFromRun(s.run), players, quotas: feasibility.quotas }),
      ).not.toThrow()
    }
  })

  it('never returns a suggestion beyond the balance ceiling', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    for (const s of suggestions) {
      expect(s.balanceDelta).toBeLessThanOrEqual(DEFAULT_MAX_BALANCE_DELTA + 1e-9)
    }
  })

  it('leaves sitters untouched in every suggestion', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const before = sitterIds(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    for (const s of suggestions) expect(sitterIds(s.run)).toEqual(before)
  })

  it('rebuilds a valid, fully-scored ScheduleRun', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    for (const s of suggestions) expect(() => scheduleRunSchema.parse(s.run)).not.toThrow()
  })

  it('ranks best-first and is deterministic', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const args = { run, players, genderMode: GENDER, feasibility, roundIndex, pair }
    const a = suggestOpponentSwaps(args)
    const b = suggestOpponentSwaps(args)
    expect(a).toEqual(b)
    for (let i = 1; i < a.length; i++) {
      const prev = a[i - 1]
      const cur = a[i]
      const ordered =
        prev.opponentRepeatDelta < cur.opponentRepeatDelta ||
        (prev.opponentRepeatDelta === cur.opponentRepeatDelta &&
          prev.balanceDelta <= cur.balanceDelta + 1e-9)
      expect(ordered).toBe(true)
    }
  })

  it('honors the limit', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
      limit: 1,
    })
    expect(suggestions.length).toBeLessThanOrEqual(1)
  })

  it('returns [] when the balance ceiling admits nothing', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
      maxBalanceDelta: -1000,
    })
    expect(suggestions).toEqual([])
  })

  it('returns [] when the pair is not an opposing pair in that round', () => {
    const { players, feasibility, run } = setup()
    // A team pairing (same court, same team) is never an opposing pair.
    const roundIndex = 0
    const team = run.rounds[0].courts[0].teams[0]
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair: [team[0], team[1]],
    })
    expect(suggestions).toEqual([])
  })

  it('returns [] for a negative roundIndex', () => {
    const { players, feasibility, run } = setup()
    const { pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex: -1,
      pair,
    })
    expect(suggestions).toEqual([])
  })

  it('returns [] for a roundIndex >= rounds.length', () => {
    const { players, feasibility, run } = setup()
    const { pair } = firstRematch(run)
    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex: run.rounds.length,
      pair,
    })
    expect(suggestions).toEqual([])
  })

  it('returns [] when one member of the pair is sitting out that round', () => {
    // setup() uses 8 players on 2 courts (0 sitters); use a 9-player roster
    // (2 courts, 1 sitter/round) so there is an actual sitter to test against.
    const players = mkRoster({ count: 9, muTop: 4.2, muStep: 0.15 })
    const courts = 2
    const rounds = 5
    const config = { preset: 'balanced' as const, seed: 7 }
    const resolved = resolveConfig({ config, tournamentId: TOURNAMENT })
    const feasibility = auditFeasibility({
      players,
      courts,
      rounds,
      genderMode: GENDER,
      config: resolved,
    })
    const run = generateSchedule({
      tournamentId: TOURNAMENT,
      players,
      courts,
      rounds,
      genderMode: GENDER,
      config,
    })

    const roundIndex = run.rounds.findIndex((r) => r.sitters.length > 0)
    expect(roundIndex).toBeGreaterThanOrEqual(0)
    const sitter = run.rounds[roundIndex].sitters[0].playerId
    const playing = run.rounds[roundIndex].courts[0].teams[0][0]

    const suggestions = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair: [playing, sitter],
    })
    expect(suggestions).toEqual([])
  })

  it('applying a suggestion removes the rematch (re-suggest finds nothing to fix)', () => {
    const { players, feasibility, run } = setup()
    const { roundIndex, pair } = firstRematch(run)
    const [best] = suggestOpponentSwaps({
      run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    expect(best).toBeDefined()
    const after = suggestOpponentSwaps({
      run: best.run,
      players,
      genderMode: GENDER,
      feasibility,
      roundIndex,
      pair,
    })
    expect(after).toEqual([])
  })
})
